Fix build error of redirect in getStaticProps
Error: `redirect` can not be returned from getStaticProps during prerendering
Caused by new redirection logic
Solution: do not generate any page of [...pathToRedirectFrom].js during building time, use ISR instead